"""empty message

Revision ID: b8db35796faf
Revises: 
Create Date: 2026-05-01 01:16:44.282367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8db35796faf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###
